Refactor catalog page, add grid, hover/active states for header, footer
htmlacademy-adaptive/990059-pink-21 pull request #10
Opened 2021-01-05 12:54 UTC by qKIRASAN

2021-01-05 18:25 UTC, Shramkoweb requested changes

2021-01-05 18:25 UTC, Shramkoweb commented on source/sass/blocks/header.scss
> +  &[href]:hover .logo__icon {
Аналогично. 1 блок влияет сам на себя только

2021-01-05 18:25 UTC, Shramkoweb commented on source/sass/blocks/main-nav.scss
> +  &[href]:hover {
Точно href прям надо?

2021-01-05 18:25 UTC, Shramkoweb commented on source/sass/blocks/user-post.scss
> +    &:first-child {
Нужно прям :first-child ? Почему решил имено так?

2021-01-06 05:18 UTC, qKIRASAN commented on source/sass/blocks/footer.scss
> +  &[href]:hover .logo__icon--glasses,
Исправил

2021-01-06 05:19 UTC, qKIRASAN commented on source/sass/blocks/header.scss
> +  &[href]:hover .logo__icon {
Исправил

2021-01-06 05:21 UTC, qKIRASAN commented on source/sass/blocks/footer.scss
> +  &[href]:active .logo__icon--glasses,
Есть ))). На главной странице логотип без атрибута href

2021-01-06 05:22 UTC, qKIRASAN commented on source/sass/blocks/main-nav.scss
> +  &[href]:hover {
Активная ссылка идёт без атрибута href

2021-01-06 05:59 UTC, qKIRASAN commented on source/sass/blocks/user-post.scss
> +    &:first-child {
Когда делал показалось, что исходя из структуры макета, фотка дня будет в единственном экземпляре и непременно первая ))). А сейчас задумался почему "в единственном", почему "непременно первая"... Ведь ничего не мешает чередовать мелкие и полноразмерные фото на странице ))). В общем переделал на модификатор.

2021-01-06 08:45 UTC, Shramkoweb commented on source/sass/blocks/develop.scss
> +    fill-opacity: 0.3;
Да, это когда цвет нужно с полупрозрачностью)

2021-01-06 08:47 UTC, Shramkoweb commented on source/catalog.html
> +                <div class="range__toggle range__toggle--crop range__toggle--active" tabindex="0"></div>
Пока оставь

2021-01-06 08:48 UTC, Shramkoweb approved these changes

2021-01-06 08:48 UTC, merged