Module5 task1
htmlacademy-adaptive/990059-pink-21 pull request #11
Opened 2021-01-12 19:31 UTC by qKIRASAN

2021-01-12 19:54 UTC, Shramkoweb commented
![image](https://user-imag@qKIRASAN s.githubusercontent.com/42001531/104365509-be014200-5520-11eb-839b-6931ef2dc5c2.png)
@

2021-01-12 20:00 UTC, Shramkoweb requested changes

2021-01-12 20:00 UTC, Shramkoweb commented on source/js/main.js
> +  event.preventDefault();
Зачем?

2021-01-12 20:00 UTC, Shramkoweb commented on source/sass/blocks/features.scss
> +  & br {
😄

2021-01-12 20:00 UTC, Shramkoweb commented on source/sass/blocks/header.scss
> +        }
Я бы это вынес наверх.

А то внутри одного медиа у тебя :before. А потом внутри бефора еще медия появилось

2021-01-12 20:00 UTC, Shramkoweb commented on source/sass/blocks/tariff.scss
> +  &--top-left {
Сильно)

2021-01-16 13:45 UTC, qKIRASAN commented on source/js/main.js
> +  event.preventDefault();
В данном случае незачем. Удалил

2021-01-16 13:49 UTC, qKIRASAN commented on source/sass/blocks/header.scss
> +        }
Согласен. Исправил

2021-01-16 13:53 UTC, qKIRASAN commented
> 
> 
> ![image](https://user-images.githubusercontent.com/42001531/104365535-c9546d80-5520-11eb-803e-43c647ee0544.png)
> 
> @qKIRASAN

Исправил

2021-01-16 16:18 UTC, Shramkoweb approved these changes

2021-01-16 16:18 UTC, merged