Add form page markup
htmlacademy-adaptive/990059-pink-21 pull request #3
Opened 2020-11-16 20:24 UTC by qKIRASAN

2020-11-16 20:59 UTC, Shramkoweb requested changes

2020-11-16 20:59 UTC, Shramkoweb commented on source/form.html
> +        <svg class="logo__icon-glasses" width="59" height="40" viewBox="0 0 59 40" fill="none" xmlns="http://www.w3.org/2000/svg">
Думаю пока не нужно все 3 логотипа. Вам потом расскажут что как

2020-11-16 20:59 UTC, Shramkoweb commented on source/form.html
> +      <p>Поделитесь своей историей и получите шанс выиграть ценный приз — 1000 миль на вашу бонусную карту! <span class="visually-hidden">Пожалуйста, заполните форму ниже:</span></p>
Зачем этот скрытый <span class="visually-hidden">Пожалуйста, заполните форму ниже:</span> ?

2020-11-16 20:59 UTC, Shramkoweb commented on source/form.html
> +          <legend class="contest-form__group-title visually-hidden">Представьтесь</legend>
legend все таки как по мне, нужен для обобщения текущей группы инпутов.

Что делает эта группа? Представьтесь - как то не про то)

2020-11-16 20:59 UTC, Shramkoweb commented on source/form.html
> +            <label><input class="contest-form__group-input" type="checkbox" name="achievement" value="Сделал селфи с акулой" checked> <span>Сделал селфи с акулой</span></label>
А чего тут инпут уже внутри лейбла?
А раньше ты отдельно через for делал? Есть логика или просто?

2020-11-16 20:59 UTC, Shramkoweb commented on source/form.html
> +        <div class="contest-form__group">
Тут филдсет не подойдет?

2020-11-16 20:59 UTC, Shramkoweb commented on source/form.html
> +      <button class="form-button" type="button">Ок</button>
А что делает кнопка формы внутри модалки? form-button

2020-11-17 17:26 UTC, qKIRASAN commented on source/form.html
> +      <p>Поделитесь своей историей и получите шанс выиграть ценный приз — 1000 миль на вашу бонусную карту! <span class="visually-hidden">Пожалуйста, заполните форму ниже:</span></p>
Предложение "Пожалуйста, заполните форму ниже:" скрыто в мобильной версии. Ошибка в h1, т.к. элемент в мобильной версии не скрыт. Исправил.

2020-11-17 17:33 UTC, qKIRASAN commented on source/form.html
> +        <svg class="logo__icon-glasses" width="59" height="40" viewBox="0 0 59 40" fill="none" xmlns="http://www.w3.org/2000/svg">
Я понимаю, что здесь уместно использовать спрайт, чтобы не плодить лишних запросов на сервер. Предлагаю править логотип после того, как загрузим контентную графику и начнём работать со спрайтами.

2020-11-17 17:40 UTC, qKIRASAN commented on source/form.html
> +          <legend class="contest-form__group-title visually-hidden">Представьтесь</legend>
Исправил на "Введите персональные данные", но, как-то не то..
Учитывая стилистику остальных legend: "Ваши безбашенные достижения в путешествии", "С каким приложением путешествовали?", хочется добавить в 1й legend лёгкости и задать неформальный тон, поэтому и было "Представьтесь".

2020-11-17 17:47 UTC, qKIRASAN commented on source/form.html
> +            <label><input class="contest-form__group-input" type="checkbox" name="achievement" value="Сделал селфи с акулой" checked> <span>Сделал селфи с акулой</span></label>
Здесь будет удобней стилизовать состояния кастомных чекбоксов и далее радио кнопок. Плюс не придётся возиться с непростым неймингом id, связывая чекбоксы с лейблом ))).

2020-11-17 17:55 UTC, qKIRASAN commented on source/form.html
> +        <div class="contest-form__group">
Я посчитал, что в данном случае не подойдёт, т.к. элемент textarea размещён в отдельном блоке и не является составной частью группы интерактивных элементов. В предыдущих блоках филдсет объединял несколько интерактивных элементов в 1 группу.

2020-11-17 18:11 UTC, qKIRASAN commented on source/form.html
> +      <button class="form-button" type="button">Ок</button>
Согласен, название класса выбрано не удачно. Сравнил кнопки на всех страницах. Используется один фонт-фэмели, фон-вейт и фонт-стайл. Решил использовать блок .button + модификатор.

2020-11-17 19:02 UTC, Shramkoweb approved these changes

2020-11-17 19:02 UTC, merged