Стилизация главной страницы
htmlacademy-adaptive/990059-pink-21 pull request #5
Opened 2020-11-29 10:53 UTC by qKIRASAN

2020-11-29 10:58 UTC, qKIRASAN commented on package-lock.json
> +  "name": "pink-21",
Вручную я этот файл не трогал

2020-11-29 11:14 UTC, qKIRASAN commented on source/index.html
> +          <path fill-rule="evenodd" clip-rule="evenodd" d="M53.8917 6.58616L58.9302 27.7312C59.0013 27.9491 59.0184 28.1815 58.98 28.4078C58.9417 28.6341 58.849 28.8472 58.7102 29.0284C58.5715 29.209
Пока удалил fill из svg и задаю цвет через .class {fill: }. Но кажется логичным оставлять fill в разметке с чёрным цветом (изображая цвет по умолчанию, т.к. без css svg без fill не отобразится) и задавать цвет через .class path {fill: }. Что скажешь по этому поводу?

2020-11-29 11:18 UTC, qKIRASAN commented on source/index.html
> +              <td class="tariff__option-container slider__item"><span class="tariff__option tariff__option--selected">Розовый фильтр</span></td>
Немного переделал таблицу. На планшете и десктопе спан с текстом и иконкой будет скрываться, а к контейнеру соответствующая иконка будет добавляться

2020-11-29 14:07 UTC, Shramkoweb commented on package-lock.json
> +  "name": "pink-21",
Это косяк академии =)

2020-11-29 14:09 UTC, Shramkoweb commented on source/index.html
> +          <path fill-rule="evenodd" clip-rule="evenodd" d="M53.8917 6.58616L58.9302 27.7312C59.0013 27.9491 59.0184 28.1815 58.98 28.4078C58.9417 28.6341 58.849 28.8472 58.7102 29.0284C58.5715 29.209
Убирать fill - это хорошая идея, а еще лучше fill - currentColor

И тогда с наружи можно через класс давать цвет. https://css-tricks.com/cascading-svg-fill-color/

2020-11-29 14:23 UTC, Shramkoweb requested changes

2020-11-29 14:23 UTC, Shramkoweb commented on source/img/no.svg
> +<svg width="27" height="27" viewBox="0 0 27 27" fill="none" xmlns="http://www.w3.org/2000/svg">
Может имя иконки дать cross ?
no - как то не ясно, что за иконка не смотрев на нее =)

2020-11-29 14:23 UTC, Shramkoweb commented on source/img/yes.svg
> +<svg width="31" height="21" viewBox="0 0 31 21" fill="none" xmlns="http://www.w3.org/2000/svg">
А тут check

2020-11-29 14:23 UTC, Shramkoweb commented on source/sass/blocks/button.scss
> +.button--round {
Модификаторы можно через `&`. 
Как удобнее?

2020-11-29 14:23 UTC, Shramkoweb commented on source/sass/blocks/features.scss
> +  //background-color: $complementary-light;
Убирай если не нужно

2020-11-29 14:23 UTC, Shramkoweb commented on source/sass/blocks/features.scss
> +.features__image-container--disabled {
Модификатор можно через &

2020-11-29 14:23 UTC, Shramkoweb commented on source/sass/blocks/feedback.scss
> +  list-style: none;
Для сбрасывания стилей списков создай миксин и просто юзай его везде

2020-11-29 14:23 UTC, Shramkoweb commented on source/sass/blocks/header.scss
> +  &--js-on {
А тут уже используешь =)
нужно выбрать единый формат написания

2020-11-29 14:23 UTC, Shramkoweb commented on source/sass/blocks/logo.scss
> +.logo__icon-glasses {
Мне кажется вот этот элемент лучше сделать модификатором?

2020-11-29 14:23 UTC, Shramkoweb commented on source/sass/blocks/logo.scss
> +.logo__icon-pink {
И этот

2020-11-29 14:23 UTC, Shramkoweb commented on source/sass/blocks/main-nav.scss
> +  &::after {
&::after и &::before почти весь код дублируется. Напиши все что общее через 
```
&::before,
&::after {}
```
А потом добавь отдельно то еще нужно

2020-11-29 14:23 UTC, Shramkoweb commented on source/sass/blocks/main-nav.scss
> +.main-nav__toggle--close {
Модификатор тут опять отдельно... =)

2020-11-29 14:23 UTC, Shramkoweb commented on source/sass/blocks/main-nav.scss
> +  list-style: none;
Миксин

2020-11-29 14:23 UTC, Shramkoweb commented on source/sass/blocks/main-nav.scss
> +    inset 0 1px 0 rgba($basic-white, 0.15);
Отступ поехал

2020-11-29 14:23 UTC, Shramkoweb commented on source/sass/blocks/page.scss
> +  font-family: "Open Sans", "Helvetica", "Arial", sans-serif;
3х достаточно, вроде даже ест критерий почитай

2020-11-29 14:23 UTC, Shramkoweb commented on source/sass/blocks/tariffs.scss
> +  //background-color: $complementary-light;
Удалить

2020-11-29 14:23 UTC, Shramkoweb commented on source/sass/global/global.scss
> +*,
html {
 box-sizing: border-box
}

А все остальные наследуют 

`*::before,
*::after {
  box-sizing: inherit;
}`

Это более гибкий вариант, и не прийдется потом в будущем каждому менять боксовую модель, если вдруг надо

2020-12-03 17:20 UTC, qKIRASAN commented on source/img/no.svg
> +<svg width="27" height="27" viewBox="0 0 27 27" fill="none" xmlns="http://www.w3.org/2000/svg">
Согласен. Изменил

2020-12-03 17:20 UTC, qKIRASAN commented on source/img/yes.svg
> +<svg width="31" height="21" viewBox="0 0 31 21" fill="none" xmlns="http://www.w3.org/2000/svg">
Согласен. Изменил

2020-12-03 17:28 UTC, qKIRASAN commented on source/sass/blocks/features.scss
> +  //background-color: $complementary-light;
Вот пока не знаю. Есть у меня мысли повесить псевдоэлемент и поиграться с бордером и vw. Понятно, что при 100vw может появиться горизонтальный скролл, а если если уменьшить возможно в ПП не попаду. Или не стоит заморачиваться, ты как считаешь?

2020-12-03 18:12 UTC, qKIRASAN commented on source/sass/blocks/button.scss
> +.button--round {
Привёл к единообразию. Добавил модификаторы и псевдоэлементы через &

2020-12-03 18:12 UTC, qKIRASAN commented on source/sass/blocks/features.scss
> +.features__image-container--disabled {
Привёл к единообразию. Добавил модификаторы и псевдоэлементы через &

2020-12-03 18:14 UTC, qKIRASAN commented on source/sass/blocks/tariffs.scss
> +  //background-color: $complementary-light;
Удалил

2020-12-03 18:15 UTC, qKIRASAN commented on source/sass/global/global.scss
> +*,
Интересный вариант, спасибо. Возьму на заметку.

2020-12-03 18:16 UTC, qKIRASAN commented on source/sass/blocks/page.scss
> +  font-family: "Open Sans", "Helvetica", "Arial", sans-serif;
Да, по критерию 3х достаточно. Просто взял 2 самых распространённых

2020-12-03 18:25 UTC, qKIRASAN commented on source/sass/blocks/main-nav.scss
> +    inset 0 1px 0 rgba($basic-white, 0.15);
Не совсем понял, какой отступ поехал. Тень двойная (внешняя + внутренняя). По макету, вроде норм

2020-12-03 18:48 UTC, qKIRASAN commented on source/sass/blocks/main-nav.scss
> +  list-style: none;
Миксин создал, подключил.

2020-12-03 20:27 UTC, Shramkoweb commented on source/sass/blocks/main-nav.scss
> +    inset 0 1px 0 rgba($basic-white, 0.15);
Ага, не заметил

2020-12-03 21:16 UTC, Shramkoweb approved these changes

2020-12-03 21:16 UTC, merged