Add mobile style to catalog page
htmlacademy-adaptive/990059-pink-21 pull request #7
Opened 2020-12-06 11:49 UTC by qKIRASAN

2020-12-06 11:55 UTC, qKIRASAN commented on source/catalog.html
> +              <div class="range__toggle" style="left: 83%;" tabindex="0"></div>
Подготовка для js.

2020-12-06 11:57 UTC, qKIRASAN commented on source/catalog.html
>              <div class="range__controls range__controls--disabled">
При больших разрешения tools скрывается, а все range показываются.

2020-12-06 12:00 UTC, Shramkoweb commented on source/catalog.html
> +              <div class="range__toggle" style="left: 83%;" tabindex="0"></div>
Выглядит так себе. Вынеси это в стили - исходные значения. А JS у тебя потом скак-то сам будет менять, что нужно инайном.

2020-12-06 12:00 UTC, Shramkoweb commented on source/catalog.html
>              <div class="range__controls range__controls--disabled">
В стили =)

2020-12-06 12:02 UTC, qKIRASAN commented on source/catalog.html
> +              <div class="range__toggle" style="left: 83%;" tabindex="0"></div>
Хорошо, понял.

2020-12-06 12:05 UTC, Shramkoweb requested changes

2020-12-06 12:05 UTC, Shramkoweb commented on source/catalog.html
> +            <img src="https://via.placeholder.com/320x137" width="320" height="137" alt="Панорамный обзор излучины реки с пилона моста солнечным летним днём. Видны холмы, покрытые густопосаженными де
задайте фоновые цвета и фоновые изображения для блоков;
Это по заданию уже должно быть

2020-12-06 12:05 UTC, Shramkoweb commented on source/catalog.html
> +          <div class="upload__button-container container">
Тут точно нужен контейнер? Выглядит странно...

2020-12-07 17:01 UTC, qKIRASAN commented on source/catalog.html
> +              <div class="range__toggle" style="left: 83%;" tabindex="0"></div>
Исправил

2020-12-07 17:47 UTC, qKIRASAN commented on source/catalog.html
> +            <img src="https://via.placeholder.com/320x137" width="320" height="137" alt="Панорамный обзор излучины реки с пилона моста солнечным летним днём. Видны холмы, покрытые густопосаженными де
Фоновый цвет задал, изображения контент.

2020-12-07 17:56 UTC, qKIRASAN commented on source/catalog.html
> +          <div class="upload__button-container container">
Пока склоняюсь к тому, что нужен. Контейнером я центрирую кнопки, тут 4 группы элементов и общая обёртка с позишн релатив и 100vw. А элементом upload позиционирую кнопки. На десктопе кнопки в линию встают, удобно будет флексом.

2020-12-07 20:27 UTC, merged