Refactor index page, add grid
htmlacademy-adaptive/990059-pink-21 pull request #8
Opened 2020-12-27 18:46 UTC by qKIRASAN

2020-12-27 18:56 UTC, qKIRASAN commented on source/index.html
> +    <!--Состояние по умолчанию, при отключенном js (критерий Б30). При включенном js header-default заменяется на header с помощью скрипта -->
Упростил логику работы (как мне кажется) при включенном js. Создал отдельный блок с элементами для загрузки по умолчанию. При включенном js блок и элементы заменяются.

2020-12-27 19:00 UTC, qKIRASAN commented on source/index.html
> +      <svg class="logo__initial" width="74" height="23" viewBox="0 0 74 23" fill="none" xmlns="http://www.w3.org/2000/svg">
Заинлайнил 3 svg для отображения логотипа в 3х вариациях

2020-12-27 19:05 UTC, qKIRASAN commented on source/index.html
> +          <b class="contacts__method contacts__method--left">Звоните:</b>
Модификаторы использую чисто для ПП. В реальной разработке контент ведь просто центрируется?

2020-12-27 19:08 UTC, qKIRASAN commented on source/index.html
> +        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1998.6036253002965!2d30.320858715898993!3d59.9387191690544!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4696310fca145
Обязательно ли в iframe прописывать width и height?

2020-12-27 19:09 UTC, qKIRASAN commented on source/index.html
> +  <a class="logo footer__logo">
В футере также заинлайнил 2 svg для отображения логотипа

2020-12-27 19:19 UTC, qKIRASAN commented on source/sass/blocks/page.scss
> +.page__container {
Решил центрировать контент через элемент блока page, чтобы не создавать блок-центровщик. Насколько я понимаю, в чистом БЭМ блоке не может быть позиционирования и маргинов. Допустимо ли использовать позишн релатив и паддинги в БЭМ блоке?

2020-12-27 19:26 UTC, qKIRASAN commented on source/sass/mixin/viewport-width-100.scss
>  @mixin viewport-width-100 {
Подсмотрел код на css tricks, протестировал, понравился больше, чем первоначальный вариант. Понимаю, что right в данном случае не обязателен, но решил оставить, т.к. данный снипет может быть использован в языке с порядком справа налево.

2020-12-27 19:28 UTC, qKIRASAN commented on source/sass/style.scss
>  @import "blocks/container.scss";
Блок container в дальнейшем планирую удалить. Центрировать контент планирую с помощью page__container

2020-12-27 19:38 UTC, qKIRASAN commented on source/index.html
> +          <img class="features__img features__img--disabled"  src="https://via.placeholder.com/136x245" width="136" height="245" alt="Старые серые мусорные баки крупным планом. Заиграли новыми краска
Со вчерашнего дня какая-то проблема с placeholder.com, заглушки не отображаются.

2020-12-28 08:56 UTC, Shramkoweb commented on source/index.html
> +    <!--Состояние по умолчанию, при отключенном js (критерий Б30). При включенном js header-default заменяется на header с помощью скрипта -->
Вот тут немного смутила фраза - `Создал отдельный блок `. Правильно ли я понял по коду, этот код НЕ дублируется?

2020-12-28 08:56 UTC, Shramkoweb commented on source/index.html
> +    <!--Состояние по умолчанию, при отключенном js (критерий Б30). При включенном js header-default заменяется на header с помощью скрипта -->
Если можно напиши в личку, обсудим

2020-12-28 08:56 UTC, Shramkoweb commented on source/index.html
> +      <svg class="logo__initial" width="74" height="23" viewBox="0 0 74 23" fill="none" xmlns="http://www.w3.org/2000/svg">
+ потом будем переделывать на спрайт))

2020-12-28 08:57 UTC, Shramkoweb commented on source/index.html
> +          <b class="contacts__method contacts__method--left">Звоните:</b>
Не факт. Я бы заменил `contacts__method--left` на `contacts__method--call`  как-то более семантично.

2020-12-28 08:57 UTC, Shramkoweb commented on source/index.html
> +        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1998.6036253002965!2d30.320858715898993!3d59.9387191690544!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4696310fca145
Да, чтобы он как СВГ не ломал сайт пока грузим стили

2020-12-28 09:01 UTC, Shramkoweb commented on source/sass/blocks/page.scss
> +.page__container {
В жизни будет в жизни))) Все зависит от команды и насколько там настоящий БЭМ. В моей практике был такой опыт, там да - каждый блок сам по себе и может цеплять только своих элементов.

pos: relative да. Падинги тоже относятся к самому блоку и не влияют на соседей?)

2020-12-28 09:05 UTC, Shramkoweb commented on source/sass/mixin/viewport-width-100.scss
>  @mixin viewport-width-100 {
Давай посмотрим)) Если работает то ок)

2020-12-28 09:17 UTC, Shramkoweb requested changes

2020-12-28 09:17 UTC, Shramkoweb commented on source/sass/blocks/features.scss
> +    border-right: 100vw solid transparent;
Как это работает?)))

2020-12-28 09:17 UTC, Shramkoweb commented on source/sass/blocks/header-default.scss
> +.header-default {
Почему header-default - что именно в нем default ?

2020-12-28 09:17 UTC, Shramkoweb commented on source/sass/blocks/header-default.scss
> +.header-default {
Выглядит странно - приходится думать, я не люблю думать)) 🤔

2020-12-28 09:17 UTC, Shramkoweb commented on source/sass/blocks/logo.scss
> +.logo__footer-initial {
В будущем спрайт поможет нам уйти от кучи классов)

2020-12-28 09:17 UTC, Shramkoweb commented on source/sass/blocks/main-nav.scss
> +.main-nav__list-default {
Опять default =) Обьясни

2020-12-28 09:17 UTC, Shramkoweb commented on source/sass/blocks/map.scss
> +.map iframe {
Класс на iframe

2020-12-28 09:17 UTC, Shramkoweb commented on source/sass/blocks/map.scss
> +    border-top: 10vw solid $basic-white;
Это прям у тебя техника какая-то?) Расскажи

2020-12-28 09:17 UTC, Shramkoweb commented on source/sass/blocks/slider.scss
> +    background-color: transparent;
Если он не нужен - то есть свй-ство : none

2020-12-28 17:58 UTC, qKIRASAN commented on source/index.html
> +    <!--Состояние по умолчанию, при отключенном js (критерий Б30). При включенном js header-default заменяется на header с помощью скрипта -->
Исправил. Все дефолтные блоки, дублирующие код, удалил, логику открытия меню переписал

2020-12-28 17:59 UTC, qKIRASAN commented on source/index.html
> +      <svg class="logo__initial" width="74" height="23" viewBox="0 0 74 23" fill="none" xmlns="http://www.w3.org/2000/svg">
Да!

2020-12-28 18:04 UTC, qKIRASAN commented on source/index.html
> +          <b class="contacts__method contacts__method--left">Звоните:</b>
Исправил

2020-12-28 18:05 UTC, qKIRASAN commented on source/index.html
> +        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1998.6036253002965!2d30.320858715898993!3d59.9387191690544!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4696310fca145
Понял!

2020-12-28 18:07 UTC, qKIRASAN commented on source/sass/blocks/header-default.scss
> +.header-default {
Понял свою промашку ))) Все дефолтные блоки, дублирующие код, удалил.

2020-12-28 18:09 UTC, qKIRASAN commented on source/sass/blocks/main-nav.scss
> +.main-nav__list-default {
Удалил

2020-12-28 19:00 UTC, qKIRASAN commented on source/sass/blocks/map.scss
> +    border-top: 10vw solid $basic-white;
Техника следующая: позиционируем псевдоэлемент с нулевой длиной и высотой как нам нужно поверх элемента (в примере координаты 0 0), задаём нужную ширину необходимой части бордера (в примере 10vw), стиль и цвет (border-width понимает единицу vw в отличие от %), далее задаём нужную ширину остальным частям бордера, если необходимо, а цвет меняем на транспарент. Минимум необходимо указать ширину 2 частям бордера (в данном примере это border-top и border-right). Получаем, простую маску в виде треугольника или трапеции. Для родителя элемента задаём overflow: hidden.

2020-12-28 19:19 UTC, qKIRASAN commented on source/sass/blocks/map.scss
> +.map iframe {
Исправил

2020-12-28 22:08 UTC, Shramkoweb commented on source/index.html
> +          <img class="features__img features__img--disabled"  src="https://via.placeholder.com/136x245" width="136" height="245" alt="Старые серые мусорные баки крупным планом. Заиграли новыми краска
Можешь поискать аналоги, могу подсказать. Но это не критично, скоро же графика пойдет?))

2020-12-28 22:09 UTC, Shramkoweb commented on source/sass/blocks/map.scss
> +    border-top: 10vw solid $basic-white;
Где-то подсмотрел? дай ссылку если осталась)) Выглядит прикольно

2020-12-28 22:09 UTC, merged