Адаптивная сетка для страницы формы
htmlacademy-adaptive/990059-pink-21 pull request #9
Opened 2021-01-04 12:08 UTC by qKIRASAN

По поводу цвета у бордера отдельной ссылки нет. Первоначально материал мне попался в тренажёрах академии, там было несколько заданий с треугольниками (https://htmlacademy.ru/courses/88/run/25). Там как раз самая база про прозрачный фон нулевые ширина и высота. А про то, что border-width понимает единицу измерения vw, прочитал сначала на MDN, а потом в какой-то статье на CSS-LIVE.

2021-01-04 13:31 UTC, Shramkoweb requested changes

2021-01-04 13:31 UTC, Shramkoweb commented on source/form.html
> +        <textarea class="contest-form__textarea" name="user-comment" id="user-comment" placeholder="Можно прям в красках, не стесняясь в выражениях" aria-label="Введите текст"></textarea>
Убери возможность менять размер у текстаирии.

2021-01-04 13:31 UTC, Shramkoweb commented on source/sass/blocks/contest.scss
> +.contest + .footer {
Каждый файл влияет только на 1 БЭМ блок.

Возможно тут подойдет микс?

2021-01-04 13:31 UTC, Shramkoweb commented on source/sass/blocks/contest.scss
> +  overflow: hidden;
overflow: hidden; - зачем?

2021-01-04 13:31 UTC, Shramkoweb commented on source/sass/blocks/lead.scss
> +.lead.contest__lead {
Нельзя

2021-01-04 16:18 UTC, qKIRASAN commented on source/form.html
> +        <textarea class="contest-form__textarea" name="user-comment" id="user-comment" placeholder="Можно прям в красках, не стесняясь в выражениях" aria-label="Введите текст"></textarea>
Убрал

2021-01-04 16:26 UTC, qKIRASAN commented on source/sass/blocks/contest.scss
> +  overflow: hidden;
Скрывать горизонтальный скролл. Там в .contest вложен блок, у которого width - 100vw.

2021-01-04 16:36 UTC, qKIRASAN commented on source/sass/blocks/lead.scss
> +.lead.contest__lead {
Исправил

2021-01-04 16:56 UTC, qKIRASAN commented on source/sass/blocks/contest.scss
> +.contest + .footer {
Исправил

2021-01-05 07:42 UTC, Shramkoweb approved these changes

2021-01-05 07:42 UTC, merged